version : "2"
services:
  app:
    build: ./app
    volumes:
      - ./app:/node-login
    ports:
      - "8080"
    links:
      - mongo
   
  proxy:
    build: proxy
    ports:
      - "80:80"
    volumes: 
      - "./proxy:/etc/nginx/conf.d/"    

  mongo:
    image: tutum/mongodb
    ports: 
      - "27017:27017"
    environment: 
      - MONGODB_USER=urvil
      - MONGODB_DATABASE=node-login
      - MONGODB_PASS=urvilpatel  
    volumes_from:
      - mongodata
      
  mongodata:
    image: tianon/true
    volumes:
      - ~/data/mongo:/data/db
      - ~/data:/data           
